apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: application-autoscaler
spec: 
  scaleTargetRef:
    apiVersion: app/v1
    kind: Deployment 
    name: masktv-application-deployment
  minReplicas: 5
  maxReplicas: 50
  metrics:
    - type:
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60